feature/summary
YGwan/spring-chatgpt-communication pull request #10
Opened 2023-05-03 17:05 UTC by ji-hyeon97

open ai Summary 을 활용한 긴 문장 요약하기 api 구현하였습니다

2023-05-04 01:29 UTC, YGwan requested changes
Complements랑 Summarized가 같은 형식의 요청인 것 같은대 이를 한번에 처리하는게 어떨까요??
공통적인 부분이 많은 것 같아서요!!

Grammar Check와 Translate도 동일하게 처리했는대 이걸 기반으로 하면 좋을거 같아요!

2023-05-04 01:29 UTC, YGwan commented on src/main/java/communication/chatgpt/data/Summarize.java
> +public enum Summarize {
Complements에서 같이 관리하는게 어때요??
ENDPOINT하고 MODEL이 동일한거 같은대

2023-05-04 01:29 UTC, YGwan commented on src/main/java/communication/chatgpt/dto/summary/request/SummarizeParsedRequestDto.java
> +public class SummarizeParsedRequestDto {
이 클래스도 마찬가지로 CompletionsParsedRequestDto에서 관리하는게 어떨까요??
그리고 만약 길이가 길어져서 MAX_TOKENS길이보다 더 작아지면 결과값이 제대로 안나올수도 있을거 같은대 100이 충분할까요??

2023-05-04 02:29 UTC, ji-hyeon97 commented on src/main/java/communication/chatgpt/data/Summarize.java
> +public enum Summarize {
좋아요 !

2023-05-04 02:38 UTC, ji-hyeon97 commented on src/main/java/communication/chatgpt/dto/summary/request/SummarizeParsedRequestDto.java
> +public class SummarizeParsedRequestDto {
넵 좋아요 !

max_token 길이는 어느 정도가 좋을까요 ??
이전의 코드에서는 `completionsRequest.getPrompt().length() * 2` 의 형식으로 임의로 지정했는데 
현재 api의 목적은 요약이기 때문에 물론 2배로 당연히 상관없지만 어떻게 설정하는게 좋을까요 ??

2023-05-04 04:24 UTC, YGwan commented on src/main/java/communication/chatgpt/dto/summary/request/SummarizeParsedRequestDto.java
> +public class SummarizeParsedRequestDto {
길이를 특정 값으로 지정하면 만약 결과값이 너무 길어지면 중간에 끊기는 문제가 발생하더라구요
그래서 저는 이런식으로 처리햇는대 혹시 좋은 의견 잇으시면 알려주시면 좋을거 같아요!

2023-05-04 04:44 UTC, ji-hyeon97 commented on src/main/java/communication/chatgpt/dto/summary/request/SummarizeParsedRequestDto.java
> +public class SummarizeParsedRequestDto {
넵 그럼 2베로 통일 시켜 놓을 게요 !🤗

2023-05-04 16:22 UTC, YGwan requested changes
수고하셨습니다!!

근데 딱 하나만 더 확인해주세요!!
보니깐 dto 패키지의 summarize 패키지의 요청과 응답 관련 클래스들 내용이랑
Completions 패키지의 요청과 응답 관련 클래스들 내용이랑 동일하네요??

이 부분도 합치는게 낫지 않을까요?? 굳이 클래스를 다르게 둘 필요가 없다고 생각하는데 어떻게 생각하시나요??
둘다 어찌됏든 같은 url에다가 post 요청을 보내니 요청 & 응답 형식이 동일하자나요!!

2023-05-05 02:47 UTC, ji-hyeon97 commented
수정 완료했습니다 !

저희 api 응답시 비슷한 형태로 open.ai 서버로 부터 응답 받기에 `@JsonIgnoreProperties(ignoreUnknown_ = true)` 를 dto 클래스에 적용해 보는 것도 좋을 것 같습니다. (개념 check !)

2023-05-05 09:50 UTC, ecsimsw approved these changes
LGTM 😁

2023-05-05 10:30 UTC, merged