리눅스 명령어 [ chatAsk -m "메시지내용" -pri ]
YGwan/spring-chatgpt-communication pull request #3
Opened 2023-04-22 03:49 UTC by ji-hyeon97

<img width="1307" alt="스크린샷 2023-04-22 오후 12 43 31" src="https://user-images.githubusercontent.com/79920930/233760441-6b87ffdf-a4a4-41d4-9e76-2910e5493399.png">

1. model 값은 yml 파일에 작성해 두고 @value로 값을 뽑아옵니다.
2. chatAsk -m "메시지내용" -pri 에서 "메시지 내용" 부분이 shell 에서 post 요청시 content 키의 value 값으로 들어가야 한다

2023-04-24 13:31 UTC, YGwan requested changes
수고하셨습니다!

전체적으로 잘하셨네요!!

근데 Controller가 처리하는 로직이 너무 많다고 생각해요!! header나 body를 만드는 부분을 Service로직으로 빼는건 어떨까요?

전체적으로 잘하셨습니다! 한번 확인해주세요!!

2023-04-24 13:31 UTC, YGwan commented on src/main/java/communication/chatgpt/controller/ChatController.java
> +    public String ask(@RequestBody AskRequestDto askRequest) throws JsonProcessingException {
해당 부분 Service 로직으로 뺄 수 있는건 빼는것 어떻게 생각하시나요?

2023-04-24 13:31 UTC, YGwan commented on src/main/java/communication/chatgpt/dto/createchat/reqeust/AskRequestDto.java
> +package communication.chatgpt.dto.createchat.reqeust;
파일 이름 확인해주세요!!
그리고 명령어마다 나눌 필요가 있을까요??
request ,response 파일 두개만 두고 여기다가 request는 request끼리, response는 response끼리 배치하는건 어떨까요?

2023-04-24 13:31 UTC, YGwan commented on src/main/java/communication/chatgpt/dto/createchat/reqeust/AskRequestDto.java
> +    private String model;
모델을 서버에서 값을 넣어주는건 어떻게 생각하시나요??

2023-04-24 13:31 UTC, YGwan commented on src/main/java/communication/chatgpt/dto/createchat/reqeust/AskRequestDto.java
> +
줄 확인해주세요!!

2023-04-24 14:05 UTC, YGwan requested changes
수고하셨습니다!

전체적으로 잘하셨네요!!

그런데, 전체적으로 불필요한 줄띄움이 많은거 같아요
한번 확인해주시고 수정해주시면 감사하겠습니다.

2023-04-24 14:05 UTC, YGwan commented on src/main/java/communication/chatgpt/controller/ChatController.java
> +        String content = askResponseDto.getChoices().get(0).getMessage().getContent();
content 변수를 추가적으로 사용하지 말고 바로 return을 하는게 어떨까요??

2023-04-24 14:05 UTC, YGwan commented on src/main/java/communication/chatgpt/controller/ChatController.java
> +    @Value("${open-ai.chat.model}")
```java
public enum model {

    GRAMMAR_MODEL("text-davinci-edit-001");

    final private String model;

    model(String model) {
        this.model = model;
    }

    public String getModel() {
        return model;
    }
}
```


이런식으로 enum값으로 처리하는건 어떨까요??

2023-04-24 14:05 UTC, YGwan commented on src/main/java/communication/chatgpt/controller/ChatController.java
> +    @Value("${open-ai.apiUrl}")
``` java
public enum ApiUrl {

    GRAMMAR_ENDPOINT("https://api.openai.com/v1/edits");

    private final String endPoint;

    ApiUrl(String endPoint) {
        this.endPoint = endPoint;
    }

    public String getEndPoint() {
        return endPoint;
    }
}

```

이런식으로 enum값으로 처리하는건 어떨까요??

2023-04-27 12:43 UTC, ecsimsw commented on src/main/java/communication/chatgpt/controller/ChatController.java
> +        String content = askResponseDto.getChoices().get(0).getMessage().getContent();
좋은 것 같아요.

2023-04-27 13:09 UTC, ji-hyeon97 commented on src/main/java/communication/chatgpt/dto/createchat/reqeust/AskRequestDto.java
> +package communication.chatgpt.dto.createchat.reqeust;
넵 좋습니다!

2023-04-27 13:09 UTC, ji-hyeon97 commented on src/main/java/communication/chatgpt/dto/createchat/reqeust/AskRequestDto.java
> +    private String model;
완료된 이슈입니다 !

2023-04-27 13:09 UTC, ji-hyeon97 commented on src/main/java/communication/chatgpt/dto/createchat/reqeust/AskRequestDto.java
> +
넵 !

2023-04-27 13:10 UTC, ji-hyeon97 commented on src/main/java/communication/chatgpt/controller/ChatController.java
> +        String content = askResponseDto.getChoices().get(0).getMessage().getContent();
넵 inline 확인했습니다 !

2023-04-27 13:10 UTC, ji-hyeon97 commented on src/main/java/communication/chatgpt/controller/ChatController.java
> +    @Value("${open-ai.chat.model}")
넵 좋습니다 !

2023-04-27 13:10 UTC, ji-hyeon97 commented on src/main/java/communication/chatgpt/controller/ChatController.java
> +    @Value("${open-ai.apiUrl}")
넵 좋습니다 !

2023-05-01 02:14 UTC, merged